version: '3.8'
networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  fastdfs-tracker-1:
    container_name: fastdfs-tracker-1
    image: fastdfs:6.12.2
    networks:
      custom_network:
        ipv4_address: 172.20.0.2
    ports:
      - "22122:22122"
    volumes:
      - ./tracker.conf:/etc/fdfs/tracker.conf
      - ./client.conf:/etc/fdfs/client.conf
    command: tracker
    restart: always

  fastdfs-tracker-2:
    container_name: fastdfs-tracker-2
    image: fastdfs:6.12.2
    networks:
      custom_network:
        ipv4_address: 172.20.0.3
    ports:
      - "22123:22122"
    volumes:
      - ./tracker.conf:/etc/fdfs/tracker.conf
      - ./client.conf:/etc/fdfs/client.conf
    command: tracker
    restart: always


  fastdfs-storage:
    container_name: fastdfs-storage
    image: fastdfs:6.12.2
    networks:
      custom_network:
        ipv4_address: 172.20.0.4
    ports:
      - "23000:23000"
      - "8888:8888"
    volumes:
      - ./storage.conf:/etc/fdfs/storage.conf
    command: storage
    restart: always
    # depends_on:
    #   - fastdfs-tracker   

  fastdfs-exporter:
    container_name: fastdfs-exporter
    image: quay.io/maxpasserby/fastdfs-exporter:0.1.0-amd64
    networks:
      custom_network:
        ipv4_address: 172.20.0.5
    environment:
      - TRACKER_SERVER=172.20.0.2:22122;172.20.0.3:22122
    ports:
      - "9036:9036"
    # command: sleep 99999999
    restart: always
    # depends_on:
    #   - fastdfs-tracker 
