# version: '3.8'
networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  mq:
    container_name: mq
    image: ibmcom/mq:9.2.0.0-r3
    networks:
      custom_network:
        ipv4_address: 172.20.0.10
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QMSERVER"
      MQ_ENABLE_METRICS: "true"
      MQ_ADMIN_PASSWORD: "123456"
      MQ_APP_PASSWORD: "123456"
    ports:
      - "1414:1414"
      - "9443:9443"
    restart: unless-stopped

  mq-exporter:
    container_name: mq-exporter
    image: ibmmq-client:9.2.0.0
    networks:
      custom_network:
        ipv4_address: 172.20.0.11
    command:
      - /bin/sh
      - -c
      - |
        sleep 20
        cd /opt/bin/
        ./mq_prometheus \
        -log.level="debug" \
        -ibmmq.queueManager="QMSERVER" \
        -ibmmq.connName="172.20.0.10(1414)" \
        -ibmmq.channel="DEV.ADMIN.SVRCONN" \
        -ibmmq.userid="admin" \
        -ibmmq.password="123456" \
        -ibmmq.useStatus \
        -ibmmq.httpListenPort="9158"

    volumes:
      - /opt/images/ibmmq/mq_prometheus:/opt/bin/mq_prometheus
    ports:
      - "9158:9158"
    # depends_on:
    #   - mq-main
    restart: unless-stopped
